version: "3"
services:
  next:
    build:
      context: ./todo_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./todo_app:/usr/src/app
      - /app/node_modules
    command: npm run dev